<a href="https://colab.research.google.com/github/matiascr/AA/blob/master/UC1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Setup

In [6]:
from sklearn import preprocessing
import numpy as np
import pandas as pd


# Descripción de variables y valores estadísticos

In [4]:
print(X_train.mean(axis=0))
print(X_train_minmax.mean(axis=0))
print(X_train.std(axis=0))
print(X_train_minmax.std(axis=0))

[1.         0.         0.33333333]
[0.5        0.5        0.44444444]
[0.81649658 0.81649658 1.24721913]
[0.40824829 0.40824829 0.41573971]
